// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/upgrade/v1beta1/query.proto

package cosmos.upgrade.v1beta1;

public final class QueryOuterClass {
  private QueryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryCurrentPlanRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.upgrade.v1beta1.QueryCurrentPlanRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * QueryCurrentPlanRequest is the request type for the Query/CurrentPlan RPC
   * method.
   * </pre>
   *
   * Protobuf type {@code cosmos.upgrade.v1beta1.QueryCurrentPlanRequest}
   */
  public static final class QueryCurrentPlanRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.upgrade.v1beta1.QueryCurrentPlanRequest)
      QueryCurrentPlanRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryCurrentPlanRequest.newBuilder() to construct.
    private QueryCurrentPlanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryCurrentPlanRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryCurrentPlanRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryCurrentPlanRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest.class, cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest)) {
        return super.equals(obj);
      }
      cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest other = (cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryCurrentPlanRequest is the request type for the Query/CurrentPlan RPC
     * method.
     * </pre>
     *
     * Protobuf type {@code cosmos.upgrade.v1beta1.QueryCurrentPlanRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.upgrade.v1beta1.QueryCurrentPlanRequest)
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest.class, cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest.Builder.class);
      }

      // Construct using cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_descriptor;
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest getDefaultInstanceForType() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest build() {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest buildPartial() {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest result = new cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest) {
          return mergeFrom((cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest other) {
        if (other == cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.upgrade.v1beta1.QueryCurrentPlanRequest)
    }

    // @@protoc_insertion_point(class_scope:cosmos.upgrade.v1beta1.QueryCurrentPlanRequest)
    private static final cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest();
    }

    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryCurrentPlanRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryCurrentPlanRequest>() {
      @java.lang.Override
      public QueryCurrentPlanRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryCurrentPlanRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryCurrentPlanRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryCurrentPlanRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryCurrentPlanResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.upgrade.v1beta1.QueryCurrentPlanResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * plan is the current upgrade plan.
     * </pre>
     *
     * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
     * @return Whether the plan field is set.
     */
    boolean hasPlan();
    /**
     * <pre>
     * plan is the current upgrade plan.
     * </pre>
     *
     * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
     * @return The plan.
     */
    cosmos.upgrade.v1beta1.Upgrade.Plan getPlan();
    /**
     * <pre>
     * plan is the current upgrade plan.
     * </pre>
     *
     * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
     */
    cosmos.upgrade.v1beta1.Upgrade.PlanOrBuilder getPlanOrBuilder();
  }
  /**
   * <pre>
   * QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC
   * method.
   * </pre>
   *
   * Protobuf type {@code cosmos.upgrade.v1beta1.QueryCurrentPlanResponse}
   */
  public static final class QueryCurrentPlanResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.upgrade.v1beta1.QueryCurrentPlanResponse)
      QueryCurrentPlanResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryCurrentPlanResponse.newBuilder() to construct.
    private QueryCurrentPlanResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryCurrentPlanResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryCurrentPlanResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryCurrentPlanResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cosmos.upgrade.v1beta1.Upgrade.Plan.Builder subBuilder = null;
              if (plan_ != null) {
                subBuilder = plan_.toBuilder();
              }
              plan_ = input.readMessage(cosmos.upgrade.v1beta1.Upgrade.Plan.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(plan_);
                plan_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse.class, cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse.Builder.class);
    }

    public static final int PLAN_FIELD_NUMBER = 1;
    private cosmos.upgrade.v1beta1.Upgrade.Plan plan_;
    /**
     * <pre>
     * plan is the current upgrade plan.
     * </pre>
     *
     * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
     * @return Whether the plan field is set.
     */
    @java.lang.Override
    public boolean hasPlan() {
      return plan_ != null;
    }
    /**
     * <pre>
     * plan is the current upgrade plan.
     * </pre>
     *
     * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
     * @return The plan.
     */
    @java.lang.Override
    public cosmos.upgrade.v1beta1.Upgrade.Plan getPlan() {
      return plan_ == null ? cosmos.upgrade.v1beta1.Upgrade.Plan.getDefaultInstance() : plan_;
    }
    /**
     * <pre>
     * plan is the current upgrade plan.
     * </pre>
     *
     * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
     */
    @java.lang.Override
    public cosmos.upgrade.v1beta1.Upgrade.PlanOrBuilder getPlanOrBuilder() {
      return getPlan();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (plan_ != null) {
        output.writeMessage(1, getPlan());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (plan_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPlan());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse)) {
        return super.equals(obj);
      }
      cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse other = (cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse) obj;

      if (hasPlan() != other.hasPlan()) return false;
      if (hasPlan()) {
        if (!getPlan()
            .equals(other.getPlan())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPlan()) {
        hash = (37 * hash) + PLAN_FIELD_NUMBER;
        hash = (53 * hash) + getPlan().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC
     * method.
     * </pre>
     *
     * Protobuf type {@code cosmos.upgrade.v1beta1.QueryCurrentPlanResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.upgrade.v1beta1.QueryCurrentPlanResponse)
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse.class, cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse.Builder.class);
      }

      // Construct using cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (planBuilder_ == null) {
          plan_ = null;
        } else {
          plan_ = null;
          planBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_descriptor;
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse getDefaultInstanceForType() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse build() {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse buildPartial() {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse result = new cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse(this);
        if (planBuilder_ == null) {
          result.plan_ = plan_;
        } else {
          result.plan_ = planBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse) {
          return mergeFrom((cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse other) {
        if (other == cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse.getDefaultInstance()) return this;
        if (other.hasPlan()) {
          mergePlan(other.getPlan());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cosmos.upgrade.v1beta1.Upgrade.Plan plan_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.upgrade.v1beta1.Upgrade.Plan, cosmos.upgrade.v1beta1.Upgrade.Plan.Builder, cosmos.upgrade.v1beta1.Upgrade.PlanOrBuilder> planBuilder_;
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       * @return Whether the plan field is set.
       */
      public boolean hasPlan() {
        return planBuilder_ != null || plan_ != null;
      }
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       * @return The plan.
       */
      public cosmos.upgrade.v1beta1.Upgrade.Plan getPlan() {
        if (planBuilder_ == null) {
          return plan_ == null ? cosmos.upgrade.v1beta1.Upgrade.Plan.getDefaultInstance() : plan_;
        } else {
          return planBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       */
      public Builder setPlan(cosmos.upgrade.v1beta1.Upgrade.Plan value) {
        if (planBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          plan_ = value;
          onChanged();
        } else {
          planBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       */
      public Builder setPlan(
          cosmos.upgrade.v1beta1.Upgrade.Plan.Builder builderForValue) {
        if (planBuilder_ == null) {
          plan_ = builderForValue.build();
          onChanged();
        } else {
          planBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       */
      public Builder mergePlan(cosmos.upgrade.v1beta1.Upgrade.Plan value) {
        if (planBuilder_ == null) {
          if (plan_ != null) {
            plan_ =
              cosmos.upgrade.v1beta1.Upgrade.Plan.newBuilder(plan_).mergeFrom(value).buildPartial();
          } else {
            plan_ = value;
          }
          onChanged();
        } else {
          planBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       */
      public Builder clearPlan() {
        if (planBuilder_ == null) {
          plan_ = null;
          onChanged();
        } else {
          plan_ = null;
          planBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       */
      public cosmos.upgrade.v1beta1.Upgrade.Plan.Builder getPlanBuilder() {
        
        onChanged();
        return getPlanFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       */
      public cosmos.upgrade.v1beta1.Upgrade.PlanOrBuilder getPlanOrBuilder() {
        if (planBuilder_ != null) {
          return planBuilder_.getMessageOrBuilder();
        } else {
          return plan_ == null ?
              cosmos.upgrade.v1beta1.Upgrade.Plan.getDefaultInstance() : plan_;
        }
      }
      /**
       * <pre>
       * plan is the current upgrade plan.
       * </pre>
       *
       * <code>.cosmos.upgrade.v1beta1.Plan plan = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.upgrade.v1beta1.Upgrade.Plan, cosmos.upgrade.v1beta1.Upgrade.Plan.Builder, cosmos.upgrade.v1beta1.Upgrade.PlanOrBuilder> 
          getPlanFieldBuilder() {
        if (planBuilder_ == null) {
          planBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.upgrade.v1beta1.Upgrade.Plan, cosmos.upgrade.v1beta1.Upgrade.Plan.Builder, cosmos.upgrade.v1beta1.Upgrade.PlanOrBuilder>(
                  getPlan(),
                  getParentForChildren(),
                  isClean());
          plan_ = null;
        }
        return planBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.upgrade.v1beta1.QueryCurrentPlanResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.upgrade.v1beta1.QueryCurrentPlanResponse)
    private static final cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse();
    }

    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryCurrentPlanResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryCurrentPlanResponse>() {
      @java.lang.Override
      public QueryCurrentPlanResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryCurrentPlanResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryCurrentPlanResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryCurrentPlanResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.upgrade.v1beta1.QueryOuterClass.QueryCurrentPlanResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryAppliedPlanRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.upgrade.v1beta1.QueryAppliedPlanRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * name is the name of the applied plan to query for.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * name is the name of the applied plan to query for.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   * QueryCurrentPlanRequest is the request type for the Query/AppliedPlan RPC
   * method.
   * </pre>
   *
   * Protobuf type {@code cosmos.upgrade.v1beta1.QueryAppliedPlanRequest}
   */
  public static final class QueryAppliedPlanRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.upgrade.v1beta1.QueryAppliedPlanRequest)
      QueryAppliedPlanRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryAppliedPlanRequest.newBuilder() to construct.
    private QueryAppliedPlanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryAppliedPlanRequest() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryAppliedPlanRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryAppliedPlanRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest.class, cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * name is the name of the applied plan to query for.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * name is the name of the applied plan to query for.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest)) {
        return super.equals(obj);
      }
      cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest other = (cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryCurrentPlanRequest is the request type for the Query/AppliedPlan RPC
     * method.
     * </pre>
     *
     * Protobuf type {@code cosmos.upgrade.v1beta1.QueryAppliedPlanRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.upgrade.v1beta1.QueryAppliedPlanRequest)
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest.class, cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest.Builder.class);
      }

      // Construct using cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_descriptor;
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest getDefaultInstanceForType() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest build() {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest buildPartial() {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest result = new cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest) {
          return mergeFrom((cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest other) {
        if (other == cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * name is the name of the applied plan to query for.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * name is the name of the applied plan to query for.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * name is the name of the applied plan to query for.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * name is the name of the applied plan to query for.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * name is the name of the applied plan to query for.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.upgrade.v1beta1.QueryAppliedPlanRequest)
    }

    // @@protoc_insertion_point(class_scope:cosmos.upgrade.v1beta1.QueryAppliedPlanRequest)
    private static final cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest();
    }

    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryAppliedPlanRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryAppliedPlanRequest>() {
      @java.lang.Override
      public QueryAppliedPlanRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryAppliedPlanRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryAppliedPlanRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryAppliedPlanRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryAppliedPlanResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.upgrade.v1beta1.QueryAppliedPlanResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * height is the block height at which the plan was applied.
     * </pre>
     *
     * <code>int64 height = 1;</code>
     * @return The height.
     */
    long getHeight();
  }
  /**
   * <pre>
   * QueryAppliedPlanResponse is the response type for the Query/AppliedPlan RPC
   * method.
   * </pre>
   *
   * Protobuf type {@code cosmos.upgrade.v1beta1.QueryAppliedPlanResponse}
   */
  public static final class QueryAppliedPlanResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.upgrade.v1beta1.QueryAppliedPlanResponse)
      QueryAppliedPlanResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryAppliedPlanResponse.newBuilder() to construct.
    private QueryAppliedPlanResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryAppliedPlanResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryAppliedPlanResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryAppliedPlanResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              height_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse.class, cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse.Builder.class);
    }

    public static final int HEIGHT_FIELD_NUMBER = 1;
    private long height_;
    /**
     * <pre>
     * height is the block height at which the plan was applied.
     * </pre>
     *
     * <code>int64 height = 1;</code>
     * @return The height.
     */
    @java.lang.Override
    public long getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (height_ != 0L) {
        output.writeInt64(1, height_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (height_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, height_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse)) {
        return super.equals(obj);
      }
      cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse other = (cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse) obj;

      if (getHeight()
          != other.getHeight()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeight());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryAppliedPlanResponse is the response type for the Query/AppliedPlan RPC
     * method.
     * </pre>
     *
     * Protobuf type {@code cosmos.upgrade.v1beta1.QueryAppliedPlanResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.upgrade.v1beta1.QueryAppliedPlanResponse)
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse.class, cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse.Builder.class);
      }

      // Construct using cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        height_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_descriptor;
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse getDefaultInstanceForType() {
        return cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse build() {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse buildPartial() {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse result = new cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse(this);
        result.height_ = height_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse) {
          return mergeFrom((cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse other) {
        if (other == cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse.getDefaultInstance()) return this;
        if (other.getHeight() != 0L) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long height_ ;
      /**
       * <pre>
       * height is the block height at which the plan was applied.
       * </pre>
       *
       * <code>int64 height = 1;</code>
       * @return The height.
       */
      @java.lang.Override
      public long getHeight() {
        return height_;
      }
      /**
       * <pre>
       * height is the block height at which the plan was applied.
       * </pre>
       *
       * <code>int64 height = 1;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(long value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * height is the block height at which the plan was applied.
       * </pre>
       *
       * <code>int64 height = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.upgrade.v1beta1.QueryAppliedPlanResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.upgrade.v1beta1.QueryAppliedPlanResponse)
    private static final cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse();
    }

    public static cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryAppliedPlanResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryAppliedPlanResponse>() {
      @java.lang.Override
      public QueryAppliedPlanResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryAppliedPlanResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryAppliedPlanResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryAppliedPlanResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.upgrade.v1beta1.QueryOuterClass.QueryAppliedPlanResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"cosmos/upgrade/v1beta1/query.proto\022\026co" +
      "smos.upgrade.v1beta1\032\034google/api/annotat" +
      "ions.proto\032$cosmos/upgrade/v1beta1/upgra" +
      "de.proto\"\031\n\027QueryCurrentPlanRequest\"F\n\030Q" +
      "ueryCurrentPlanResponse\022*\n\004plan\030\001 \001(\0132\034." +
      "cosmos.upgrade.v1beta1.Plan\"\'\n\027QueryAppl" +
      "iedPlanRequest\022\014\n\004name\030\001 \001(\t\"*\n\030QueryApp" +
      "liedPlanResponse\022\016\n\006height\030\001 \001(\0032\320\002\n\005Que" +
      "ry\022\236\001\n\013CurrentPlan\022/.cosmos.upgrade.v1be" +
      "ta1.QueryCurrentPlanRequest\0320.cosmos.upg" +
      "rade.v1beta1.QueryCurrentPlanResponse\",\202" +
      "\323\344\223\002&\022$/cosmos/upgrade/v1beta1/current_p" +
      "lan\022\245\001\n\013AppliedPlan\022/.cosmos.upgrade.v1b" +
      "eta1.QueryAppliedPlanRequest\0320.cosmos.up" +
      "grade.v1beta1.QueryAppliedPlanResponse\"3" +
      "\202\323\344\223\002-\022+/cosmos/upgrade/v1beta1/applied_" +
      "plan/{name}B.Z,github.com/cosmos/cosmos-" +
      "sdk/x/upgrade/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          cosmos.upgrade.v1beta1.Upgrade.getDescriptor(),
        });
    internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanRequest_descriptor,
        new java.lang.String[] { });
    internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_upgrade_v1beta1_QueryCurrentPlanResponse_descriptor,
        new java.lang.String[] { "Plan", });
    internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_upgrade_v1beta1_QueryAppliedPlanResponse_descriptor,
        new java.lang.String[] { "Height", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    cosmos.upgrade.v1beta1.Upgrade.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
