// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tendermint/rpc/grpc/types.proto

package tendermint.rpc.grpc;

public final class Types {
    private Types() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface RequestPingOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tendermint.rpc.grpc.RequestPing)
            com.google.protobuf.MessageOrBuilder {
    }

    /**
     * Protobuf type {@code tendermint.rpc.grpc.RequestPing}
     */
    public static final class RequestPing extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tendermint.rpc.grpc.RequestPing)
            RequestPingOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use RequestPing.newBuilder() to construct.
        private RequestPing(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RequestPing() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new RequestPing();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private RequestPing(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestPing_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestPing_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            tendermint.rpc.grpc.Types.RequestPing.class, tendermint.rpc.grpc.Types.RequestPing.Builder.class);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof tendermint.rpc.grpc.Types.RequestPing)) {
                return super.equals(obj);
            }
            tendermint.rpc.grpc.Types.RequestPing other = (tendermint.rpc.grpc.Types.RequestPing) obj;

            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.RequestPing parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(tendermint.rpc.grpc.Types.RequestPing prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code tendermint.rpc.grpc.RequestPing}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tendermint.rpc.grpc.RequestPing)
                tendermint.rpc.grpc.Types.RequestPingOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestPing_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestPing_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                tendermint.rpc.grpc.Types.RequestPing.class, tendermint.rpc.grpc.Types.RequestPing.Builder.class);
            }

            // Construct using tendermint.rpc.grpc.Types.RequestPing.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestPing_descriptor;
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.RequestPing getDefaultInstanceForType() {
                return tendermint.rpc.grpc.Types.RequestPing.getDefaultInstance();
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.RequestPing build() {
                tendermint.rpc.grpc.Types.RequestPing result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.RequestPing buildPartial() {
                tendermint.rpc.grpc.Types.RequestPing result = new tendermint.rpc.grpc.Types.RequestPing(this);
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof tendermint.rpc.grpc.Types.RequestPing) {
                    return mergeFrom((tendermint.rpc.grpc.Types.RequestPing) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(tendermint.rpc.grpc.Types.RequestPing other) {
                if (other == tendermint.rpc.grpc.Types.RequestPing.getDefaultInstance()) return this;
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                tendermint.rpc.grpc.Types.RequestPing parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (tendermint.rpc.grpc.Types.RequestPing) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tendermint.rpc.grpc.RequestPing)
        }

        // @@protoc_insertion_point(class_scope:tendermint.rpc.grpc.RequestPing)
        private static final tendermint.rpc.grpc.Types.RequestPing DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new tendermint.rpc.grpc.Types.RequestPing();
        }

        public static tendermint.rpc.grpc.Types.RequestPing getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RequestPing>
                PARSER = new com.google.protobuf.AbstractParser<RequestPing>() {
            @java.lang.Override
            public RequestPing parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RequestPing(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<RequestPing> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RequestPing> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public tendermint.rpc.grpc.Types.RequestPing getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface RequestBroadcastTxOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tendermint.rpc.grpc.RequestBroadcastTx)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes tx = 1;</code>
         *
         * @return The tx.
         */
        com.google.protobuf.ByteString getTx();
    }

    /**
     * Protobuf type {@code tendermint.rpc.grpc.RequestBroadcastTx}
     */
    public static final class RequestBroadcastTx extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tendermint.rpc.grpc.RequestBroadcastTx)
            RequestBroadcastTxOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use RequestBroadcastTx.newBuilder() to construct.
        private RequestBroadcastTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RequestBroadcastTx() {
            tx_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new RequestBroadcastTx();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private RequestBroadcastTx(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {

                            tx_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestBroadcastTx_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestBroadcastTx_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            tendermint.rpc.grpc.Types.RequestBroadcastTx.class, tendermint.rpc.grpc.Types.RequestBroadcastTx.Builder.class);
        }

        public static final int TX_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString tx_;

        /**
         * <code>bytes tx = 1;</code>
         *
         * @return The tx.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getTx() {
            return tx_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!tx_.isEmpty()) {
                output.writeBytes(1, tx_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!tx_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, tx_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof tendermint.rpc.grpc.Types.RequestBroadcastTx)) {
                return super.equals(obj);
            }
            tendermint.rpc.grpc.Types.RequestBroadcastTx other = (tendermint.rpc.grpc.Types.RequestBroadcastTx) obj;

            if (!getTx()
                    .equals(other.getTx())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TX_FIELD_NUMBER;
            hash = (53 * hash) + getTx().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(tendermint.rpc.grpc.Types.RequestBroadcastTx prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code tendermint.rpc.grpc.RequestBroadcastTx}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tendermint.rpc.grpc.RequestBroadcastTx)
                tendermint.rpc.grpc.Types.RequestBroadcastTxOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestBroadcastTx_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestBroadcastTx_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                tendermint.rpc.grpc.Types.RequestBroadcastTx.class, tendermint.rpc.grpc.Types.RequestBroadcastTx.Builder.class);
            }

            // Construct using tendermint.rpc.grpc.Types.RequestBroadcastTx.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                tx_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_RequestBroadcastTx_descriptor;
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.RequestBroadcastTx getDefaultInstanceForType() {
                return tendermint.rpc.grpc.Types.RequestBroadcastTx.getDefaultInstance();
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.RequestBroadcastTx build() {
                tendermint.rpc.grpc.Types.RequestBroadcastTx result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.RequestBroadcastTx buildPartial() {
                tendermint.rpc.grpc.Types.RequestBroadcastTx result = new tendermint.rpc.grpc.Types.RequestBroadcastTx(this);
                result.tx_ = tx_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof tendermint.rpc.grpc.Types.RequestBroadcastTx) {
                    return mergeFrom((tendermint.rpc.grpc.Types.RequestBroadcastTx) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(tendermint.rpc.grpc.Types.RequestBroadcastTx other) {
                if (other == tendermint.rpc.grpc.Types.RequestBroadcastTx.getDefaultInstance()) return this;
                if (other.getTx() != com.google.protobuf.ByteString.EMPTY) {
                    setTx(other.getTx());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                tendermint.rpc.grpc.Types.RequestBroadcastTx parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (tendermint.rpc.grpc.Types.RequestBroadcastTx) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.ByteString tx_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes tx = 1;</code>
             *
             * @return The tx.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getTx() {
                return tx_;
            }

            /**
             * <code>bytes tx = 1;</code>
             *
             * @param value The tx to set.
             * @return This builder for chaining.
             */
            public Builder setTx(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                tx_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes tx = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTx() {

                tx_ = getDefaultInstance().getTx();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tendermint.rpc.grpc.RequestBroadcastTx)
        }

        // @@protoc_insertion_point(class_scope:tendermint.rpc.grpc.RequestBroadcastTx)
        private static final tendermint.rpc.grpc.Types.RequestBroadcastTx DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new tendermint.rpc.grpc.Types.RequestBroadcastTx();
        }

        public static tendermint.rpc.grpc.Types.RequestBroadcastTx getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RequestBroadcastTx>
                PARSER = new com.google.protobuf.AbstractParser<RequestBroadcastTx>() {
            @java.lang.Override
            public RequestBroadcastTx parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RequestBroadcastTx(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<RequestBroadcastTx> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RequestBroadcastTx> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public tendermint.rpc.grpc.Types.RequestBroadcastTx getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ResponsePingOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tendermint.rpc.grpc.ResponsePing)
            com.google.protobuf.MessageOrBuilder {
    }

    /**
     * Protobuf type {@code tendermint.rpc.grpc.ResponsePing}
     */
    public static final class ResponsePing extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tendermint.rpc.grpc.ResponsePing)
            ResponsePingOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ResponsePing.newBuilder() to construct.
        private ResponsePing(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ResponsePing() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ResponsePing();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ResponsePing(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponsePing_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponsePing_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            tendermint.rpc.grpc.Types.ResponsePing.class, tendermint.rpc.grpc.Types.ResponsePing.Builder.class);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof tendermint.rpc.grpc.Types.ResponsePing)) {
                return super.equals(obj);
            }
            tendermint.rpc.grpc.Types.ResponsePing other = (tendermint.rpc.grpc.Types.ResponsePing) obj;

            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.ResponsePing parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(tendermint.rpc.grpc.Types.ResponsePing prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code tendermint.rpc.grpc.ResponsePing}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tendermint.rpc.grpc.ResponsePing)
                tendermint.rpc.grpc.Types.ResponsePingOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponsePing_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponsePing_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                tendermint.rpc.grpc.Types.ResponsePing.class, tendermint.rpc.grpc.Types.ResponsePing.Builder.class);
            }

            // Construct using tendermint.rpc.grpc.Types.ResponsePing.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponsePing_descriptor;
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.ResponsePing getDefaultInstanceForType() {
                return tendermint.rpc.grpc.Types.ResponsePing.getDefaultInstance();
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.ResponsePing build() {
                tendermint.rpc.grpc.Types.ResponsePing result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.ResponsePing buildPartial() {
                tendermint.rpc.grpc.Types.ResponsePing result = new tendermint.rpc.grpc.Types.ResponsePing(this);
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof tendermint.rpc.grpc.Types.ResponsePing) {
                    return mergeFrom((tendermint.rpc.grpc.Types.ResponsePing) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(tendermint.rpc.grpc.Types.ResponsePing other) {
                if (other == tendermint.rpc.grpc.Types.ResponsePing.getDefaultInstance()) return this;
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                tendermint.rpc.grpc.Types.ResponsePing parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (tendermint.rpc.grpc.Types.ResponsePing) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tendermint.rpc.grpc.ResponsePing)
        }

        // @@protoc_insertion_point(class_scope:tendermint.rpc.grpc.ResponsePing)
        private static final tendermint.rpc.grpc.Types.ResponsePing DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new tendermint.rpc.grpc.Types.ResponsePing();
        }

        public static tendermint.rpc.grpc.Types.ResponsePing getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ResponsePing>
                PARSER = new com.google.protobuf.AbstractParser<ResponsePing>() {
            @java.lang.Override
            public ResponsePing parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ResponsePing(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ResponsePing> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ResponsePing> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public tendermint.rpc.grpc.Types.ResponsePing getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ResponseBroadcastTxOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tendermint.rpc.grpc.ResponseBroadcastTx)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
         *
         * @return Whether the checkTx field is set.
         */
        boolean hasCheckTx();

        /**
         * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
         *
         * @return The checkTx.
         */
        tendermint.abci.Types.ResponseCheckTx getCheckTx();

        /**
         * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
         */
        tendermint.abci.Types.ResponseCheckTxOrBuilder getCheckTxOrBuilder();

        /**
         * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
         *
         * @return Whether the deliverTx field is set.
         */
        boolean hasDeliverTx();

        /**
         * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
         *
         * @return The deliverTx.
         */
        tendermint.abci.Types.ResponseDeliverTx getDeliverTx();

        /**
         * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
         */
        tendermint.abci.Types.ResponseDeliverTxOrBuilder getDeliverTxOrBuilder();
    }

    /**
     * Protobuf type {@code tendermint.rpc.grpc.ResponseBroadcastTx}
     */
    public static final class ResponseBroadcastTx extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tendermint.rpc.grpc.ResponseBroadcastTx)
            ResponseBroadcastTxOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ResponseBroadcastTx.newBuilder() to construct.
        private ResponseBroadcastTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ResponseBroadcastTx() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ResponseBroadcastTx();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ResponseBroadcastTx(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            tendermint.abci.Types.ResponseCheckTx.Builder subBuilder = null;
                            if (checkTx_ != null) {
                                subBuilder = checkTx_.toBuilder();
                            }
                            checkTx_ = input.readMessage(tendermint.abci.Types.ResponseCheckTx.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(checkTx_);
                                checkTx_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            tendermint.abci.Types.ResponseDeliverTx.Builder subBuilder = null;
                            if (deliverTx_ != null) {
                                subBuilder = deliverTx_.toBuilder();
                            }
                            deliverTx_ = input.readMessage(tendermint.abci.Types.ResponseDeliverTx.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(deliverTx_);
                                deliverTx_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            tendermint.rpc.grpc.Types.ResponseBroadcastTx.class, tendermint.rpc.grpc.Types.ResponseBroadcastTx.Builder.class);
        }

        public static final int CHECK_TX_FIELD_NUMBER = 1;
        private tendermint.abci.Types.ResponseCheckTx checkTx_;

        /**
         * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
         *
         * @return Whether the checkTx field is set.
         */
        @java.lang.Override
        public boolean hasCheckTx() {
            return checkTx_ != null;
        }

        /**
         * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
         *
         * @return The checkTx.
         */
        @java.lang.Override
        public tendermint.abci.Types.ResponseCheckTx getCheckTx() {
            return checkTx_ == null ? tendermint.abci.Types.ResponseCheckTx.getDefaultInstance() : checkTx_;
        }

        /**
         * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
         */
        @java.lang.Override
        public tendermint.abci.Types.ResponseCheckTxOrBuilder getCheckTxOrBuilder() {
            return getCheckTx();
        }

        public static final int DELIVER_TX_FIELD_NUMBER = 2;
        private tendermint.abci.Types.ResponseDeliverTx deliverTx_;

        /**
         * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
         *
         * @return Whether the deliverTx field is set.
         */
        @java.lang.Override
        public boolean hasDeliverTx() {
            return deliverTx_ != null;
        }

        /**
         * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
         *
         * @return The deliverTx.
         */
        @java.lang.Override
        public tendermint.abci.Types.ResponseDeliverTx getDeliverTx() {
            return deliverTx_ == null ? tendermint.abci.Types.ResponseDeliverTx.getDefaultInstance() : deliverTx_;
        }

        /**
         * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
         */
        @java.lang.Override
        public tendermint.abci.Types.ResponseDeliverTxOrBuilder getDeliverTxOrBuilder() {
            return getDeliverTx();
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (checkTx_ != null) {
                output.writeMessage(1, getCheckTx());
            }
            if (deliverTx_ != null) {
                output.writeMessage(2, getDeliverTx());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (checkTx_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getCheckTx());
            }
            if (deliverTx_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getDeliverTx());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof tendermint.rpc.grpc.Types.ResponseBroadcastTx)) {
                return super.equals(obj);
            }
            tendermint.rpc.grpc.Types.ResponseBroadcastTx other = (tendermint.rpc.grpc.Types.ResponseBroadcastTx) obj;

            if (hasCheckTx() != other.hasCheckTx()) return false;
            if (hasCheckTx()) {
                if (!getCheckTx()
                        .equals(other.getCheckTx())) return false;
            }
            if (hasDeliverTx() != other.hasDeliverTx()) return false;
            if (hasDeliverTx()) {
                if (!getDeliverTx()
                        .equals(other.getDeliverTx())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasCheckTx()) {
                hash = (37 * hash) + CHECK_TX_FIELD_NUMBER;
                hash = (53 * hash) + getCheckTx().hashCode();
            }
            if (hasDeliverTx()) {
                hash = (37 * hash) + DELIVER_TX_FIELD_NUMBER;
                hash = (53 * hash) + getDeliverTx().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(tendermint.rpc.grpc.Types.ResponseBroadcastTx prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code tendermint.rpc.grpc.ResponseBroadcastTx}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tendermint.rpc.grpc.ResponseBroadcastTx)
                tendermint.rpc.grpc.Types.ResponseBroadcastTxOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                tendermint.rpc.grpc.Types.ResponseBroadcastTx.class, tendermint.rpc.grpc.Types.ResponseBroadcastTx.Builder.class);
            }

            // Construct using tendermint.rpc.grpc.Types.ResponseBroadcastTx.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (checkTxBuilder_ == null) {
                    checkTx_ = null;
                } else {
                    checkTx_ = null;
                    checkTxBuilder_ = null;
                }
                if (deliverTxBuilder_ == null) {
                    deliverTx_ = null;
                } else {
                    deliverTx_ = null;
                    deliverTxBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return tendermint.rpc.grpc.Types.internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_descriptor;
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.ResponseBroadcastTx getDefaultInstanceForType() {
                return tendermint.rpc.grpc.Types.ResponseBroadcastTx.getDefaultInstance();
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.ResponseBroadcastTx build() {
                tendermint.rpc.grpc.Types.ResponseBroadcastTx result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public tendermint.rpc.grpc.Types.ResponseBroadcastTx buildPartial() {
                tendermint.rpc.grpc.Types.ResponseBroadcastTx result = new tendermint.rpc.grpc.Types.ResponseBroadcastTx(this);
                if (checkTxBuilder_ == null) {
                    result.checkTx_ = checkTx_;
                } else {
                    result.checkTx_ = checkTxBuilder_.build();
                }
                if (deliverTxBuilder_ == null) {
                    result.deliverTx_ = deliverTx_;
                } else {
                    result.deliverTx_ = deliverTxBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof tendermint.rpc.grpc.Types.ResponseBroadcastTx) {
                    return mergeFrom((tendermint.rpc.grpc.Types.ResponseBroadcastTx) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(tendermint.rpc.grpc.Types.ResponseBroadcastTx other) {
                if (other == tendermint.rpc.grpc.Types.ResponseBroadcastTx.getDefaultInstance()) return this;
                if (other.hasCheckTx()) {
                    mergeCheckTx(other.getCheckTx());
                }
                if (other.hasDeliverTx()) {
                    mergeDeliverTx(other.getDeliverTx());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                tendermint.rpc.grpc.Types.ResponseBroadcastTx parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (tendermint.rpc.grpc.Types.ResponseBroadcastTx) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private tendermint.abci.Types.ResponseCheckTx checkTx_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    tendermint.abci.Types.ResponseCheckTx, tendermint.abci.Types.ResponseCheckTx.Builder, tendermint.abci.Types.ResponseCheckTxOrBuilder> checkTxBuilder_;

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             *
             * @return Whether the checkTx field is set.
             */
            public boolean hasCheckTx() {
                return checkTxBuilder_ != null || checkTx_ != null;
            }

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             *
             * @return The checkTx.
             */
            public tendermint.abci.Types.ResponseCheckTx getCheckTx() {
                if (checkTxBuilder_ == null) {
                    return checkTx_ == null ? tendermint.abci.Types.ResponseCheckTx.getDefaultInstance() : checkTx_;
                } else {
                    return checkTxBuilder_.getMessage();
                }
            }

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             */
            public Builder setCheckTx(tendermint.abci.Types.ResponseCheckTx value) {
                if (checkTxBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkTx_ = value;
                    onChanged();
                } else {
                    checkTxBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             */
            public Builder setCheckTx(
                    tendermint.abci.Types.ResponseCheckTx.Builder builderForValue) {
                if (checkTxBuilder_ == null) {
                    checkTx_ = builderForValue.build();
                    onChanged();
                } else {
                    checkTxBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             */
            public Builder mergeCheckTx(tendermint.abci.Types.ResponseCheckTx value) {
                if (checkTxBuilder_ == null) {
                    if (checkTx_ != null) {
                        checkTx_ =
                                tendermint.abci.Types.ResponseCheckTx.newBuilder(checkTx_).mergeFrom(value).buildPartial();
                    } else {
                        checkTx_ = value;
                    }
                    onChanged();
                } else {
                    checkTxBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             */
            public Builder clearCheckTx() {
                if (checkTxBuilder_ == null) {
                    checkTx_ = null;
                    onChanged();
                } else {
                    checkTx_ = null;
                    checkTxBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             */
            public tendermint.abci.Types.ResponseCheckTx.Builder getCheckTxBuilder() {

                onChanged();
                return getCheckTxFieldBuilder().getBuilder();
            }

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             */
            public tendermint.abci.Types.ResponseCheckTxOrBuilder getCheckTxOrBuilder() {
                if (checkTxBuilder_ != null) {
                    return checkTxBuilder_.getMessageOrBuilder();
                } else {
                    return checkTx_ == null ?
                            tendermint.abci.Types.ResponseCheckTx.getDefaultInstance() : checkTx_;
                }
            }

            /**
             * <code>.tendermint.abci.ResponseCheckTx check_tx = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    tendermint.abci.Types.ResponseCheckTx, tendermint.abci.Types.ResponseCheckTx.Builder, tendermint.abci.Types.ResponseCheckTxOrBuilder>
            getCheckTxFieldBuilder() {
                if (checkTxBuilder_ == null) {
                    checkTxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            tendermint.abci.Types.ResponseCheckTx, tendermint.abci.Types.ResponseCheckTx.Builder, tendermint.abci.Types.ResponseCheckTxOrBuilder>(
                            getCheckTx(),
                            getParentForChildren(),
                            isClean());
                    checkTx_ = null;
                }
                return checkTxBuilder_;
            }

            private tendermint.abci.Types.ResponseDeliverTx deliverTx_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    tendermint.abci.Types.ResponseDeliverTx, tendermint.abci.Types.ResponseDeliverTx.Builder, tendermint.abci.Types.ResponseDeliverTxOrBuilder> deliverTxBuilder_;

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             *
             * @return Whether the deliverTx field is set.
             */
            public boolean hasDeliverTx() {
                return deliverTxBuilder_ != null || deliverTx_ != null;
            }

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             *
             * @return The deliverTx.
             */
            public tendermint.abci.Types.ResponseDeliverTx getDeliverTx() {
                if (deliverTxBuilder_ == null) {
                    return deliverTx_ == null ? tendermint.abci.Types.ResponseDeliverTx.getDefaultInstance() : deliverTx_;
                } else {
                    return deliverTxBuilder_.getMessage();
                }
            }

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             */
            public Builder setDeliverTx(tendermint.abci.Types.ResponseDeliverTx value) {
                if (deliverTxBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    deliverTx_ = value;
                    onChanged();
                } else {
                    deliverTxBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             */
            public Builder setDeliverTx(
                    tendermint.abci.Types.ResponseDeliverTx.Builder builderForValue) {
                if (deliverTxBuilder_ == null) {
                    deliverTx_ = builderForValue.build();
                    onChanged();
                } else {
                    deliverTxBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             */
            public Builder mergeDeliverTx(tendermint.abci.Types.ResponseDeliverTx value) {
                if (deliverTxBuilder_ == null) {
                    if (deliverTx_ != null) {
                        deliverTx_ =
                                tendermint.abci.Types.ResponseDeliverTx.newBuilder(deliverTx_).mergeFrom(value).buildPartial();
                    } else {
                        deliverTx_ = value;
                    }
                    onChanged();
                } else {
                    deliverTxBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             */
            public Builder clearDeliverTx() {
                if (deliverTxBuilder_ == null) {
                    deliverTx_ = null;
                    onChanged();
                } else {
                    deliverTx_ = null;
                    deliverTxBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             */
            public tendermint.abci.Types.ResponseDeliverTx.Builder getDeliverTxBuilder() {

                onChanged();
                return getDeliverTxFieldBuilder().getBuilder();
            }

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             */
            public tendermint.abci.Types.ResponseDeliverTxOrBuilder getDeliverTxOrBuilder() {
                if (deliverTxBuilder_ != null) {
                    return deliverTxBuilder_.getMessageOrBuilder();
                } else {
                    return deliverTx_ == null ?
                            tendermint.abci.Types.ResponseDeliverTx.getDefaultInstance() : deliverTx_;
                }
            }

            /**
             * <code>.tendermint.abci.ResponseDeliverTx deliver_tx = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    tendermint.abci.Types.ResponseDeliverTx, tendermint.abci.Types.ResponseDeliverTx.Builder, tendermint.abci.Types.ResponseDeliverTxOrBuilder>
            getDeliverTxFieldBuilder() {
                if (deliverTxBuilder_ == null) {
                    deliverTxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            tendermint.abci.Types.ResponseDeliverTx, tendermint.abci.Types.ResponseDeliverTx.Builder, tendermint.abci.Types.ResponseDeliverTxOrBuilder>(
                            getDeliverTx(),
                            getParentForChildren(),
                            isClean());
                    deliverTx_ = null;
                }
                return deliverTxBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tendermint.rpc.grpc.ResponseBroadcastTx)
        }

        // @@protoc_insertion_point(class_scope:tendermint.rpc.grpc.ResponseBroadcastTx)
        private static final tendermint.rpc.grpc.Types.ResponseBroadcastTx DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new tendermint.rpc.grpc.Types.ResponseBroadcastTx();
        }

        public static tendermint.rpc.grpc.Types.ResponseBroadcastTx getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ResponseBroadcastTx>
                PARSER = new com.google.protobuf.AbstractParser<ResponseBroadcastTx>() {
            @java.lang.Override
            public ResponseBroadcastTx parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ResponseBroadcastTx(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ResponseBroadcastTx> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ResponseBroadcastTx> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public tendermint.rpc.grpc.Types.ResponseBroadcastTx getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tendermint_rpc_grpc_RequestPing_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tendermint_rpc_grpc_RequestPing_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tendermint_rpc_grpc_RequestBroadcastTx_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tendermint_rpc_grpc_RequestBroadcastTx_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tendermint_rpc_grpc_ResponsePing_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tendermint_rpc_grpc_ResponsePing_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\037tendermint/rpc/grpc/types.proto\022\023tende" +
                        "rmint.rpc.grpc\032\033tendermint/abci/types.pr" +
                        "oto\"\r\n\013RequestPing\" \n\022RequestBroadcastTx" +
                        "\022\n\n\002tx\030\001 \001(\014\"\016\n\014ResponsePing\"\201\001\n\023Respons" +
                        "eBroadcastTx\0222\n\010check_tx\030\001 \001(\0132 .tenderm" +
                        "int.abci.ResponseCheckTx\0226\n\ndeliver_tx\030\002" +
                        " \001(\0132\".tendermint.abci.ResponseDeliverTx" +
                        "2\275\001\n\014BroadcastAPI\022K\n\004Ping\022 .tendermint.r" +
                        "pc.grpc.RequestPing\032!.tendermint.rpc.grp" +
                        "c.ResponsePing\022`\n\013BroadcastTx\022\'.tendermi" +
                        "nt.rpc.grpc.RequestBroadcastTx\032(.tenderm" +
                        "int.rpc.grpc.ResponseBroadcastTxB4Z2gith" +
                        "ub.com/tendermint/tendermint/rpc/grpc;co" +
                        "regrpcb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                tendermint.abci.Types.getDescriptor(),
                        });
        internal_static_tendermint_rpc_grpc_RequestPing_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tendermint_rpc_grpc_RequestPing_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tendermint_rpc_grpc_RequestPing_descriptor,
                new java.lang.String[]{});
        internal_static_tendermint_rpc_grpc_RequestBroadcastTx_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_tendermint_rpc_grpc_RequestBroadcastTx_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tendermint_rpc_grpc_RequestBroadcastTx_descriptor,
                new java.lang.String[]{"Tx",});
        internal_static_tendermint_rpc_grpc_ResponsePing_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_tendermint_rpc_grpc_ResponsePing_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tendermint_rpc_grpc_ResponsePing_descriptor,
                new java.lang.String[]{});
        internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tendermint_rpc_grpc_ResponseBroadcastTx_descriptor,
                new java.lang.String[]{"CheckTx", "DeliverTx",});
        tendermint.abci.Types.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
